export default function(){
  return[
      {
          id: 1,
          name:'Home',
          address:"5733 Fountain Flat Dr, Fort Worth, TX 76244",
          state:'TX',
          position:{lat:32.9048,lng:-97.262085},
          price:237540,
          bedrooms:4,
          bathrooms:3,
          sqft:2230,
          type:'Single Family',
          year:'2011',
          heating:'Forced air',
          cooling:'Central',
          parking:2,
          lotsqft:5488,
          pricepersqfr:107,
          imageAmount:35,
          description:'Spacious and Open 4 Bedroom 3 Full Bath home in sought after Keller ISD! The downstairs living room is bright and open to the kitchen perfect for family and entertaining. Kitchen offers plenty of cabinets and storage with SS appliances. There is one bedroom down with a full bath, would make great guest suite. Second living and 3 bedrooms upstairs. Large master, room for sitting area, dual sinks and separate shower, with jetted tub. Nice sized back yard with covered patio. Walk to the community pool and playground!'
      },
      {
          id: 2,
          name:'Home',
          address:"3100 Hamilton Ave, Fort Worth, TX 76107",
          state:'TX',
          position:{lat:32.7547,lng:-97.3614},
          price:325000,
          bedrooms:1,
          bathrooms:1,
          sqft:2230,
          type:'Apartment',
          year:'2011',
          heating:'Forced air',
          cooling:'Central',
          parking:2,
          lotsqft:5488,
          pricepersqfr:107,
          description:"well hello there"
      },
      {
          id: 2,
          name:'Home',
          address:"3100 Hamilton Ave, Fort Worth, TX 76107",
          state:'TX',
          position:{lat:32.7357,lng:-97.10841},
          price:325000,
          bedrooms:1,
          bathrooms:1,
          sqft:2230,
          type:'Apartment',
          year:'2011',
          heating:'Forced air',
          cooling:'Central',
          parking:2,
          lotsqft:5488,
          pricepersqfr:107,
          description:"well hello there"
      }
  ]
}
