import React, { Component } from 'react';
import InfoPageTemplate from '../InfoPageTemplate/InfoPageTemplate';

const ServicesPage = ()=>{

  return(
    <InfoPageTemplate headerImage = "/images/info-pages/local-services.jpg" title = "We're Your Local Real Estate Resource">
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Condimentum lacinia quis vel eros donec ac odio tempor. Ornare arcu dui vivamus arcu felis bibendum ut. Maecenas volutpat blandit aliquam etiam erat velit. Duis ut diam quam nulla porttitor massa id. Egestas pretium aenean pharetra magna. Bibendum enim facilisis gravida neque convallis a cras. Risus quis varius quam quisque id diam vel quam. Morbi tincidunt ornare massa eget. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Senectus et netus et malesuada fames. Varius quam quisque id diam vel quam. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Dui faucibus in ornare quam viverra orci sagittis. Dolor sit amet consectetur adipiscing elit. </p>
      <p> Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Eget duis at tellus at urna condimentum mattis pellentesque. Velit laoreet id donec ultrices tincidunt arcu. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Dui accumsan sit amet nulla facilisi morbi. Neque volutpat ac tincidunt vitae. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Ut sem viverra aliquet eget sit amet tellus. Libero justo laoreet sit amet cursus sit. Elementum sagittis vitae et leo duis. Arcu risus quis varius quam quisque id diam. Adipiscing bibendum est ultricies integer quis auctor elit. Quam pellentesque nec nam aliquam sem. Habitant morbi tristique senectus et netus et. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Cras pulvinar mattis nunc sed blandit libero volutpat. Quam quisque id diam vel quam elementum. Elit sed vulputate mi sit amet mauris. Turpis egestas integer eget aliquet nibh praesent tristique. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et.</p>
      <p>Ultrices dui sapien eget mi proin sed libero enim sed. Augue mauris augue neque gravida in fermentum et sollicitudin. Ipsum faucibus vitae aliquet nec ullamcorper sit amet. Libero enim sed faucibus turpis in. Non tellus orci ac auctor augue. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Sit amet luctus venenatis lectus. Bibendum at varius vel pharetra vel turpis nunc eget. Proin nibh nisl condimentum id. Non tellus orci ac auctor augue mauris augue neque gravida.</p>
      <p> Varius duis at consectetur lorem donec massa sapien. Nunc sed augue lacus viverra vitae congue. Imperdiet proin fermentum leo vel orci porta non. Orci nulla pellentesque dignissim enim sit amet. Turpis egestas pretium aenean pharetra magna ac. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Non odio euismod lacinia at quis risus sed vulputate. Iaculis nunc sed augue lacus viverra vitae. Lobortis elementum nibh tellus molestie nunc non blandit massa. Auctor eu augue ut lectus. Lacus viverra vitae congue eu consequat. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Viverra nam libero justo laoreet sit. Accumsan in nisl nisi scelerisque eu. </p>
    </InfoPageTemplate>
  )

}

export default ServicesPage;
